test:
	echo "No tests run since this is a Spade playground project"
	echo '<testsuites name="results"><testsuite name="all" package="all"><property name="random_seed" value="1732265775" /></testsuite></testsuites>' > results.xml

clean:
	echo "No-op"